name: e_frontend
description: Loja e-commerce.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/coffeIMG.jpg
    - assets/icone/Icon.png
  fonts:
        - family: Roboto
          fonts:
            - asset: assets/fonts/Roboto-Regular.ttf
        - family: Ubuntu
          fonts:
            - asset: assets/fonts/Ubuntu-Regular.ttf
          
 

  
  